apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
spec:
  selector:
    matchLabels:
      app: plex
      tier: plex
  replicas: 1
  template:
    metadata:
      labels:
        app: plex
        tier: plex
    spec:
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: version
          value: docker
        name: plex
        image: lscr.io/linuxserver/plex
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 32400
          hostPort: 32400
          name: plex-port
          protocol: TCP
      hostNetwork: true
      restartPolicy: Always
